# Generated by Django 6.0.8 on 2026-08-18 12:52

import apps.events.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("starts_at", models.DateTimeField()),
                ("doors_open_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, help_text="Blank means four hours after the start.", null=True)),
                ("venue", models.CharField(blank=True, max_length=200)),
                ("venue_lat", models.FloatField(blank=True, null=True)),
                ("venue_lng", models.FloatField(blank=True, null=True)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=0, help_text="0 means no limit."
                    ),
                ),
                ("pack_url", models.URLField(blank=True, help_text="Launch pack, for brokers who cannot travel to Bryanston.")),
                ("rsvp_closes_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-starts_at",),
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(blank=True, max_length=80)),
                ("company", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "msisdn",
                    models.CharField(
                        blank=True,
                        help_text="International form, no plus.",
                        max_length=32,
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("broker", "Broker"),
                            ("vip", "VIP"),
                            ("press", "Press"),
                            ("staff", "Cinagi staff"),
                        ],
                        default="broker",
                        max_length=20,
                    ),
                ),
                (
                    "invite_token",
                    models.CharField(
                        default=apps.events.models.new_token, max_length=32, unique=True
                    ),
                ),
                (
                    "ticket_token",
                    models.CharField(
                        default=apps.events.models.new_token, max_length=32, unique=True
                    ),
                ),
                ("guest_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("engaged", "Started a chat"),
                            ("confirmed", "RSVP complete"),
                            ("reconfirmed", "Confirmed the day before"),
                            ("checked_in", "Checked in"),
                            ("feedback", "Gave feedback"),
                            ("alumni", "Post-event"),
                            ("stopped", "Opted out"),
                        ],
                        default="invited",
                        max_length=20,
                    ),
                ),
                (
                    "rsvp_status",
                    models.CharField(
                        choices=[
                            ("none", "Not answered"),
                            ("attending", "Coming in person"),
                            ("pack", "Outside Gauteng - wants the launch pack"),
                            ("declined", "Cannot make it"),
                            ("waitlist", "On the waitlist"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("party_size", models.PositiveSmallIntegerField(default=1)),
                ("dietary", models.CharField(blank=True, max_length=120)),
                ("interests", models.JSONField(blank=True, default=list)),
                ("invite_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("first_message_at", models.DateTimeField(blank=True, null=True)),
                ("rsvp_at", models.DateTimeField(blank=True, null=True)),
                ("reconfirmed_at", models.DateTimeField(blank=True, null=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("feedback_rating", models.CharField(blank=True, max_length=40)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked the moment they message us.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_guests",
                        to="contacts.contact",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="events.event",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("last_name", "first_name"),
            },
        ),
        migrations.CreateModel(
            name="JourneyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.CharField(max_length=40)),
                ("detail", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey",
                        to="events.guest",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="guest",
            index=models.Index(
                fields=["event", "stage"], name="events_gues_event_i_c355a0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="guest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("msisdn", ""), _negated=True),
                fields=("event", "msisdn"),
                name="uniq_guest_number_per_event",
            ),
        ),
    ]
