# Generated by Django 6.0.8 on 2026-08-27 08:53

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_secret',
            field=apps.core.fields.EncryptedTextField(blank=True, default='', help_text="Shared secret for the website registration form. The form's webhook must send it back to us; leave blank to keep the form endpoint switched off."),
        ),
    ]
