# Generated by Django 6.0.8 on 2026-08-27 13:20

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_registration_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='id_number',
            field=apps.core.fields.EncryptedTextField(blank=True, default='', help_text='ID or passport number, for venue access.'),
        ),
    ]
