# Generated by Django 6.0.8 on 2026-09-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_login_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_on_enter',
            field=models.BooleanField(default=True, help_text='In a chat, Enter sends the message and Shift+Enter starts a new line.'),
        ),
    ]
