# Generated by Django 6.0.8 on 2026-08-18 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wa_id",
                    models.CharField(
                        help_text="WhatsApp id: the phone number in full international form, no +.",
                        max_length=32,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=120)),
                (
                    "profile_name",
                    models.CharField(
                        blank=True,
                        help_text="The name they set on their own WhatsApp profile.",
                        max_length=120,
                    ),
                ),
                ("locale", models.CharField(blank=True, max_length=12)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("is_blocked", models.BooleanField(default=False)),
                ("opted_out_at", models.DateTimeField(blank=True, null=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_seen_at",),
            },
        ),
        migrations.CreateModel(
            name="ContactConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("service", "Service messages"),
                            ("marketing", "Marketing messages"),
                            ("ai_processing", "AI assistance"),
                        ],
                        max_length=32,
                    ),
                ),
                ("granted", models.BooleanField(default=True)),
                ("source", models.CharField(blank=True, max_length=120)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="contacts.contact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactExternalRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("xealth", "Xealth / BIMS"),
                            ("crm", "CRM"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("external_id", models.CharField(max_length=120)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_refs",
                        to="contacts.contact",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["workspace", "wa_id"], name="contacts_co_workspa_c64fbe_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("workspace", "wa_id"), name="uniq_contact_per_workspace"
            ),
        ),
        migrations.AddConstraint(
            model_name="contactconsent",
            constraint=models.UniqueConstraint(
                fields=("contact", "purpose"), name="uniq_contact_consent"
            ),
        ),
        migrations.AddConstraint(
            model_name="contactexternalref",
            constraint=models.UniqueConstraint(
                fields=("contact", "system", "external_id"),
                name="uniq_contact_external_ref",
            ),
        ),
    ]
