# Generated by Django 6.0.8 on 2026-09-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pending_alert_at',
            field=models.DateTimeField(blank=True, help_text='When the people on duty were last told this chat is waiting for a reply.', null=True),
        ),
    ]
