# Generated by Django 6.0.8 on 2026-09-09 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_conversation_pending_alert_at'),
        ('library', '0002_bulk_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='bulk_send',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='library.bulksend'),
        ),
    ]
