# Generated by Django 6.0.8 on 2026-09-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_fix_unassigned_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Voice note'), ('sticker', 'Sticker'), ('location', 'Location'), ('contacts', 'Contact card'), ('interactive', 'Menu reply'), ('button', 'Button tap'), ('template', 'Template'), ('unsupported', 'Unsupported')], default='text', max_length=20),
        ),
    ]
