# Generated by Django 6.0.8 on 2026-09-11 05:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_audience'),
        ('inbox', '0005_questions'),
        ('library', '0003_template_status_detail'),
        ('workspaces', '0002_membership_rights'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entries', models.PositiveSmallIntegerField(default=1)),
                ('reason', models.CharField(max_length=120)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_entries', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PrizeDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('winner_entries', models.PositiveIntegerField()),
                ('total_entries', models.PositiveIntegerField()),
                ('people', models.PositiveIntegerField()),
                ('drawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prizes_won', to='contacts.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="How the team refers to it, e.g. 'Q1 exercise'.", max_length=120)),
                ('thanks_text', models.TextField(blank=True, help_text='Sent back the first time someone answers. Leave blank to send nothing.')),
                ('counts_as_entry', models.BooleanField(default=True, help_text='Each person who answers earns one prize-draw entry.')),
                ('is_active', models.BooleanField(default=True, help_text='Switched-off questions stop counting answers.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.OneToOneField(help_text='The approved template whose quick-reply buttons are the answers.', on_delete=django.db.models.deletion.PROTECT, related_name='question', to='library.messagetemplate')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='Must match the button text exactly.', max_length=60)),
                ('value', models.SlugField(help_text='Short code stored with the answer, e.g. three_plus.', max_length=60)),
                ('score', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('audience', models.ForeignKey(blank=True, help_text='People who choose this answer are added to this audience.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contacts.audience')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(blank=True, max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('first_answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('taps', models.PositiveSmallIntegerField(default=1)),
                ('bulk_send', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='library.bulksend')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='contacts.contact')),
                ('reply_message', models.ForeignKey(blank=True, help_text='The latest tap or reply that set this answer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.message')),
                ('sent_message', models.ForeignKey(blank=True, help_text='The template message this answered.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.message')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='questions.answeroption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question')),
            ],
            options={
                'ordering': ('-answered_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='answeroption',
            constraint=models.UniqueConstraint(fields=('question', 'label'), name='uniq_option_label_per_question'),
        ),
        migrations.AddConstraint(
            model_name='answeroption',
            constraint=models.UniqueConstraint(fields=('question', 'value'), name='uniq_option_value_per_question'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('question', 'contact'), name='uniq_answer_per_person'),
        ),
    ]
