# Generated by Django 6.0.8 on 2026-09-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Archived questions keep their answers but leave the list and the prize draw.', null=True),
        ),
    ]
