# Generated by Django 6.0.8 on 2026-08-18 07:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "timezone",
                    models.CharField(default="Africa/Johannesburg", max_length=64),
                ),
                (
                    "accent_colour",
                    models.CharField(
                        default="#0f766e",
                        help_text="Shown around the inbox so agents always know which number they are on.",
                        max_length=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                (
                    "auto_assign_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Automatically give new chats to an available agent",
                    ),
                ),
                (
                    "queue_timeout_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Escalate to a supervisor if nobody picks up a chat in this time.",
                    ),
                ),
                (
                    "sticky_agent_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Send a returning customer back to the agent who last helped them.",
                    ),
                ),
                (
                    "out_of_hours_message",
                    models.TextField(
                        blank=True,
                        default="Thanks for your message. Our team is offline right now and will reply when we open.",
                    ),
                ),
                ("send_out_of_hours_message", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=120)),
                ("recurring_annually", models.BooleanField(default=False)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("date",),
            },
        ),
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("opens_at", models.TimeField(default=datetime.time(8, 0))),
                ("closes_at", models.TimeField(default=datetime.time(17, 0))),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_hours",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "business hours",
                "ordering": ("weekday",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "weekday"), name="uniq_hours_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Administrator"),
                            ("supervisor", "Supervisor"),
                            ("agent", "Agent"),
                            ("viewer", "Viewer"),
                        ],
                        default="agent",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "workspace"), name="uniq_membership"
                    )
                ],
            },
        ),
    ]
