# Generated by Django 6.0.8 on 2026-09-09 11:11

from django.db import migrations, models


def grant_to_existing_managers(apps, schema_editor):
    """Owners and administrators could already do both; keep it that way."""
    WorkspaceMembership = apps.get_model("workspaces", "WorkspaceMembership")
    WorkspaceMembership.objects.filter(role__in=["owner", "admin"]).update(
        can_send_bulk=True, can_edit_hours=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemembership',
            name='can_edit_hours',
            field=models.BooleanField(default=False, help_text='May change working hours and holidays.'),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='can_send_bulk',
            field=models.BooleanField(default=False, help_text='May send an approved message to whole audiences.'),
        ),
        migrations.RunPython(grant_to_existing_managers, migrations.RunPython.noop),
    ]
