# Generated by Django 6.0.8 on 2026-08-18 07:37

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "display_name",
                    models.CharField(
                        help_text="What your team calls this number, e.g. Claims Support",
                        max_length=120,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="The number customers message, e.g. +27 11 123 4567",
                        max_length=32,
                    ),
                ),
                (
                    "phone_number_id",
                    models.CharField(
                        help_text="Phone number ID - copy it from WhatsApp Manager > API Setup.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "waba_id",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp Business Account ID (for templates).",
                        max_length=64,
                    ),
                ),
                (
                    "access_token",
                    apps.core.fields.EncryptedTextField(
                        blank=True,
                        help_text="Permanent system user token from Meta. Stored encrypted.",
                    ),
                ),
                (
                    "app_secret",
                    apps.core.fields.EncryptedTextField(
                        blank=True,
                        help_text="Meta app secret - used to prove webhooks really came from Meta.",
                    ),
                ),
                ("verify_token", models.CharField(blank=True, max_length=64)),
                ("graph_version", models.CharField(blank=True, max_length=10)),
                ("is_default", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Not connected yet"),
                            ("connected", "Connected"),
                            ("error", "Needs attention"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("status_detail", models.CharField(blank=True, max_length=255)),
                ("quality_rating", models.CharField(blank=True, max_length=20)),
                ("messaging_limit", models.CharField(blank=True, max_length=40)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_inbound_at", models.DateTimeField(blank=True, null=True)),
                ("templates_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("display_name",),
            },
        ),
    ]
